### ISSUE TITLE
Breaks in angular 4.3, material "^2.0.0-beta.11"

### ISSUE THREAD

**Issue by moorthi07** [SamVerschueren/ngx-monaco#7]
ERROR Error: Uncaught (in promise): TypeError: __WEBPACK_IMPORTED_MODULE_3_rxjs_Observable__.Observable.create(...).pipe is not a function
TypeError: __WEBPACK_IMPORTED_MODULE_3_rxjs_Observable__.Observable.create(...).pipe is not a function
    at new MonacoEditorService (ngx-monaco.es5.js:8508)

- I see you have used angular 5  and the name shows ng'x' . Have you tested in ng 4.0? or it won't work in ng 4.0?

**Comment by SamVerschueren** [comment]
You have to upgrade RxJS. I'm using [pipeable operators](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md), which was added in RxJS 5.5. It's best practice to start using them as they reduce your bundle size.

**Comment by moorthi07** [comment]
Thanks.  This error is fixed with rxjs update.
